[target.thumbv7em-none-eabihf]
runner = "probe-rs run --protocol swd --speed 1000 --chip STM32H7R3Z8Jx"
rustflags = [
  "-C",
  "linker=flip-link",
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"
