[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32H7R3Z8Jx"
rustflags = [
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace,embassy_usb_synopsys_otg=debug"
